### ISSUE TITLE
"." in devicenames (like "fritz.box") creates wrong states

### ISSUE THREAD

**Issue by Apollon77** [soef/ioBroker.tr-064#5] opened 2016-11-16 09:32 UTC
my fritz.box (default name) created a "fritz" state with "box "under it and because of this none of the child states were created.

"." needs to be removed or replaced out ...

**Comment by soef** [comment] 2016-11-16 21:43
Can I have some more information? "fritz.box" is usual and works.

**Comment by Apollon77** [comment] 2016-11-16 21:59
<img width="767" alt="bildschirmfoto 2016-11-16 um 22 56 22" src="https://cloud.githubusercontent.com/assets/11976694/20367550/4d379bc8-ac50-11e6-9cfb-c432d3cbdda4.png">

The states are created this way ... yes it works ( so the subkeys are there), but "unexpected" a bit :-)

**Comment by soef** [comment] 2016-11-16 22:32
I see. What os and what node Version do you use? Do you have installed an old Version? If, try to deinstall and reinstall.

**Comment by Apollon77** [comment] 2016-11-17 07:24
node 4.6 on Ubuntu Xenial on Cubietruck. I installed 0.1.6 initially and now 0.1.8 yesterday.
what it should look like according to the source code?

**Comment by soef** [comment] 2016-11-17 08:30
The problem is fixed in Version 0.1.9. Thank you for your help.

**Closed** 2016-12-21 11:52 UTC
